name: Checkout repository and verify Java installation on GitHub actions runner # nazwa workflow
 on: [push, workflow_dispatch] # eventy, na które reaguje workflow
 jobs:
 checkout_and_verify_java: # nazwa joba
   name: Test workflow # nazwa akcji
   runs-on: ubuntu-latest
   steps: # definicje kroków
     - name: Checkout the latest Git commit
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Setup JDK
       uses: actions/setup-java@v2
       with:
        java-version: '17'
        distribution: 'adopt'
     - name: Verify Java installation
       run: java -version

# test